version: "3.8"

services:

  mysql:
    image: mysql:8.0
    container_name: mysql_api
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: hotelsys_db
      MYSQL_USER: hotelsys_user
      MYSQL_PASSWORD: hotelsys_pass
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Docker/MySQL/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: spring_api
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/hotelsys_db
      SPRING_DATASOURCE_USERNAME: hotelsys_user
      SPRING_DATASOURCE_PASSWORD: hotelsys_pass

volumes:
  mysql_data:
